version: '3.8'

services:
  wordpress:
    image: wordpress:php8.1-fpm
    container_name: wordpress
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
    volumes:
      - ./wp-data:/var/www/html
    depends_on:
      - db
    networks:
      - wp-network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./wp-data:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - wordpress
    networks:
      - wp-network

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wp-network

volumes:
  db_data:

networks:
  wp-network:
    driver: bridge
